// Code generated by typed-id. DO NOT EDIT.

package testdata

import (
	"database/sql/driver"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"strconv"
)

// --- Methods for UserID ---

// String implements fmt.Stringer.
func (id UserID) String() string {
	return string(id)
}

// MarshalText implements encoding.TextMarshaler.
func (id UserID) MarshalText() ([]byte, error) {
	return []byte(id), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *UserID) UnmarshalText(text []byte) error {
	*id = UserID(text)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (id UserID) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(id))
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *UserID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*id = UserID(s)
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (id UserID) MarshalBinary() ([]byte, error) {
	return []byte(id), nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (id *UserID) UnmarshalBinary(data []byte) error {
	*id = UserID(data)
	return nil
}

// Value implements driver.Valuer.
func (id UserID) Value() (driver.Value, error) {
	return string(id), nil
}

// Scan implements sql.Scanner.
func (id *UserID) Scan(src any) error {
	if src == nil {
		*id = ""
		return nil
	}
	switch v := src.(type) {
	case string:
		*id = UserID(v)
		return nil
	case []byte:
		*id = UserID(v)
		return nil
	default:
		return fmt.Errorf("cannot scan %T into %s", src, "UserID")
	}
}

// --- Methods for AccountID ---

// String implements fmt.Stringer.
func (id AccountID) String() string {
	return strconv.FormatInt(int64(id), 10)
}

// MarshalText implements encoding.TextMarshaler.
func (id AccountID) MarshalText() ([]byte, error) {
	return []byte(strconv.FormatInt(int64(id), 10)), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *AccountID) UnmarshalText(text []byte) error {
	v, err := strconv.ParseInt(string(text), 10, 64)
	if err != nil {
		return err
	}
	*id = AccountID(v)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (id AccountID) MarshalJSON() ([]byte, error) {
	return json.Marshal(int64(id))
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *AccountID) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*id = AccountID(v)
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (id AccountID) MarshalBinary() ([]byte, error) {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(id))
	return b, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (id *AccountID) UnmarshalBinary(data []byte) error {
	if len(data) != 8 {
		return fmt.Errorf("invalid binary length for %s: got %d, expected 8", "AccountID", len(data))
	}
	*id = AccountID(binary.BigEndian.Uint64(data))
	return nil
}

// Value implements driver.Valuer.
func (id AccountID) Value() (driver.Value, error) {
	return int64(id), nil
}

// Scan implements sql.Scanner.
func (id *AccountID) Scan(src any) error {
	if src == nil {
		*id = 0
		return nil
	}
	switch v := src.(type) {
	case int64:
		*id = AccountID(v)
		return nil
	case int:
		*id = AccountID(v)
		return nil
	case int32:
		*id = AccountID(v)
		return nil
	case int16:
		*id = AccountID(v)
		return nil
	case int8:
		*id = AccountID(v)
		return nil
	case uint:
		*id = AccountID(v)
		return nil
	case uint64:
		*id = AccountID(v)
		return nil
	case uint32:
		*id = AccountID(v)
		return nil
	case uint16:
		*id = AccountID(v)
		return nil
	case uint8:
		*id = AccountID(v)
		return nil
	case []byte:
		val, err := strconv.ParseInt(string(v), 10, 64)
		if err != nil {
			return err
		}
		*id = AccountID(val)
		return nil
	case string:
		val, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return err
		}
		*id = AccountID(val)
		return nil
	case float64:
		*id = AccountID(int64(v))
		return nil
	default:
		return fmt.Errorf("cannot scan %T into %s", src, "AccountID")
	}
}

// --- Methods for RoleID ---

// String implements fmt.Stringer.
func (id RoleID) String() string {
	return strconv.FormatUint(uint64(id), 10)
}

// MarshalText implements encoding.TextMarshaler.
func (id RoleID) MarshalText() ([]byte, error) {
	return []byte(strconv.FormatUint(uint64(id), 10)), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *RoleID) UnmarshalText(text []byte) error {
	v, err := strconv.ParseUint(string(text), 10, 32)
	if err != nil {
		return err
	}
	*id = RoleID(v)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (id RoleID) MarshalJSON() ([]byte, error) {
	return json.Marshal(uint64(id))
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *RoleID) UnmarshalJSON(data []byte) error {
	var v uint64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*id = RoleID(v)
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (id RoleID) MarshalBinary() ([]byte, error) {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(id))
	return b, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (id *RoleID) UnmarshalBinary(data []byte) error {
	if len(data) != 8 {
		return fmt.Errorf("invalid binary length for %s: got %d, expected 8", "RoleID", len(data))
	}
	*id = RoleID(binary.BigEndian.Uint64(data))
	return nil
}

// Value implements driver.Valuer.
func (id RoleID) Value() (driver.Value, error) {
	return int64(id), nil
}

// Scan implements sql.Scanner.
func (id *RoleID) Scan(src any) error {
	if src == nil {
		*id = 0
		return nil
	}
	switch v := src.(type) {
	case uint64:
		*id = RoleID(v)
		return nil
	case uint:
		*id = RoleID(v)
		return nil
	case uint32:
		*id = RoleID(v)
		return nil
	case uint16:
		*id = RoleID(v)
		return nil
	case uint8:
		*id = RoleID(v)
		return nil
	case int64:
		*id = RoleID(v)
		return nil
	case int:
		*id = RoleID(v)
		return nil
	case int32:
		*id = RoleID(v)
		return nil
	case int16:
		*id = RoleID(v)
		return nil
	case int8:
		*id = RoleID(v)
		return nil
	case []byte:
		val, err := strconv.ParseUint(string(v), 10, 32)
		if err != nil {
			return err
		}
		*id = RoleID(val)
		return nil
	case string:
		val, err := strconv.ParseUint(v, 10, 32)
		if err != nil {
			return err
		}
		*id = RoleID(val)
		return nil
	case float64:
		*id = RoleID(uint64(v))
		return nil
	default:
		return fmt.Errorf("cannot scan %T into %s", src, "RoleID")
	}
}

// --- Methods for SmallID ---

// String implements fmt.Stringer.
func (id SmallID) String() string {
	return strconv.FormatInt(int64(id), 10)
}

// MarshalText implements encoding.TextMarshaler.
func (id SmallID) MarshalText() ([]byte, error) {
	return []byte(strconv.FormatInt(int64(id), 10)), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *SmallID) UnmarshalText(text []byte) error {
	v, err := strconv.ParseInt(string(text), 10, 8)
	if err != nil {
		return err
	}
	*id = SmallID(v)
	return nil
}

// MarshalJSON implements json.Marshaler.
func (id SmallID) MarshalJSON() ([]byte, error) {
	return json.Marshal(int64(id))
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *SmallID) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*id = SmallID(v)
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (id SmallID) MarshalBinary() ([]byte, error) {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(id))
	return b, nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (id *SmallID) UnmarshalBinary(data []byte) error {
	if len(data) != 8 {
		return fmt.Errorf("invalid binary length for %s: got %d, expected 8", "SmallID", len(data))
	}
	*id = SmallID(binary.BigEndian.Uint64(data))
	return nil
}

// Value implements driver.Valuer.
func (id SmallID) Value() (driver.Value, error) {
	return int64(id), nil
}

// Scan implements sql.Scanner.
func (id *SmallID) Scan(src any) error {
	if src == nil {
		*id = 0
		return nil
	}
	switch v := src.(type) {
	case int64:
		*id = SmallID(v)
		return nil
	case int:
		*id = SmallID(v)
		return nil
	case int32:
		*id = SmallID(v)
		return nil
	case int16:
		*id = SmallID(v)
		return nil
	case int8:
		*id = SmallID(v)
		return nil
	case uint:
		*id = SmallID(v)
		return nil
	case uint64:
		*id = SmallID(v)
		return nil
	case uint32:
		*id = SmallID(v)
		return nil
	case uint16:
		*id = SmallID(v)
		return nil
	case uint8:
		*id = SmallID(v)
		return nil
	case []byte:
		val, err := strconv.ParseInt(string(v), 10, 8)
		if err != nil {
			return err
		}
		*id = SmallID(val)
		return nil
	case string:
		val, err := strconv.ParseInt(v, 10, 8)
		if err != nil {
			return err
		}
		*id = SmallID(val)
		return nil
	case float64:
		*id = SmallID(int64(v))
		return nil
	default:
		return fmt.Errorf("cannot scan %T into %s", src, "SmallID")
	}
}
