package main

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"sort"
	"strings"
)

// Preset represents a code generation preset.
type Preset string

const (
	PresetText   Preset = "text"
	PresetJSON   Preset = "json"
	PresetBinary Preset = "binary"
	PresetBinder Preset = "binder"
	PresetSQL    Preset = "sql"
	PresetDB     Preset = "db"
	PresetAll    Preset = "all"
)

// NormalizePresets normalizes a list of preset strings into distinct canonical presets.
// "all" expands to text, json, binary, binder, sql.
// "db" is mapped to "sql".
func NormalizePresets(presets []Preset) ([]Preset, error) {
	if len(presets) == 0 {
		return []Preset{PresetText, PresetJSON, PresetBinary, PresetBinder, PresetSQL}, nil
	}

	set := make(map[Preset]bool)
	for _, p := range presets {
		p = Preset(strings.ToLower(strings.TrimSpace(string(p))))
		switch p {
		case PresetAll:
			set[PresetText] = true
			set[PresetJSON] = true
			set[PresetBinary] = true
			set[PresetBinder] = true
			set[PresetSQL] = true
		case PresetText:
			set[PresetText] = true
		case PresetJSON:
			set[PresetJSON] = true
		case PresetBinary:
			set[PresetBinary] = true
		case PresetSQL, PresetDB:
			set[PresetSQL] = true
		case PresetBinder:
			set[PresetBinder] = true
		case "":
			continue
		default:
			return nil, fmt.Errorf("unknown preset %q (supported: text, json, binary, sql, db, all)", p)
		}
	}

	var result []Preset
	for _, p := range []Preset{PresetText, PresetJSON, PresetBinary, PresetBinder, PresetSQL} {
		if set[p] {
			result = append(result, p)
		}
	}

	return result, nil
}

// BitSizeForType returns the bit size for strconv.ParseInt / strconv.ParseUint.
func BitSizeForType(typeName string) int {
	switch typeName {
	case "int8", "uint8", "byte":
		return 8 //nolint:mnd // 8 bits
	case "int16", "uint16":
		return 16 //nolint:mnd // 16 bits
	case "int32", "uint32":
		return 32 //nolint:mnd // 32 bits
	case "int64", "uint64":
		return 64 //nolint:mnd // 64 bits
	default:
		return 0
	}
}

// GenerateOptions contains configuration for code generation.
type GenerateOptions struct {
	PackageName string      // Generated package name (defaults to target package)
	Types       []*TypeInfo // Target types to generate for
	Presets     []Preset    // Enabled presets
}

// Generate creates formatted Go source code for the requested types and presets.
func Generate(opts GenerateOptions) ([]byte, error) {
	if len(opts.Types) == 0 {
		return nil, fmt.Errorf("no types provided for code generation")
	}

	presets, err := NormalizePresets(opts.Presets)
	if err != nil {
		return nil, err
	}

	pkgName := opts.PackageName
	if pkgName == "" {
		pkgName = opts.Types[0].PackageName
	}

	hasPreset := func(p Preset) bool {
		return slices.Contains(presets, p)
	}

	// Determine required imports
	importAliases := make(map[string]string)
	importAliases["github.com/pudottapommin/golib/pkg/uuid"] = "guid"

	importSet := make(map[string]bool)
	for _, t := range opts.Types {
		if hasPreset(PresetText) {
			if t.Kind == KindInt || t.Kind == KindUint {
				importSet["strconv"] = true
			} else if t.Kind == KindUUID {
				importSet["uuid"] = true
			}
		}
		if hasPreset(PresetJSON) {
			importSet["encoding/json/jsontext"] = true
			importSet["encoding/json/v2"] = true
			if t.Kind == KindUUID {
				importSet["uuid"] = true
			}
		}
		if hasPreset(PresetBinary) {
			if t.Kind == KindInt || t.Kind == KindUint {
				importSet["encoding/binary"] = true
				importSet["fmt"] = true
			} else if t.Kind == KindUUID {
				importSet["uuid"] = true
			}
		}
		if hasPreset(PresetBinder) {
			//importSet["github.com/pudottapommin/golib/http/binding"] = true
			importSet["fmt"] = true
			if t.Kind == KindInt || t.Kind == KindUint {
				importSet["strconv"] = true
			} else if t.Kind == KindUUID {
				importSet["github.com/pudottapommin/golib/pkg/uuid"] = true
			}
		}
		if hasPreset(PresetSQL) {
			importSet["database/sql/driver"] = true
			importSet["fmt"] = true
			if t.Kind == KindInt || t.Kind == KindUint {
				importSet["strconv"] = true
			} else if t.Kind == KindUUID {
				importSet["uuid"] = true
			}
		}
	}

	var imports []string
	for imp := range importSet {
		imports = append(imports, imp)
	}
	sort.Strings(imports)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by typed-id. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imports {
			if alias, ok := importAliases[imp]; ok {
				buf.WriteString(fmt.Sprintf("\t%s %q\n", alias, imp))
				continue
			}
			buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		buf.WriteString(")\n\n")
	}

	for i, t := range opts.Types {
		if i > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString(fmt.Sprintf("// --- Methods for %s ---\n\n", t.Name))

		if hasPreset(PresetText) {
			buf.WriteString(generateTextPreset(t))
		}
		if hasPreset(PresetJSON) {
			buf.WriteString(generateJSONPreset(t))
		}
		if hasPreset(PresetBinary) {
			buf.WriteString(generateBinaryPreset(t))
		}
		if hasPreset(PresetBinder) {
			buf.WriteString(generateBinderPreset(t))
		}
		if hasPreset(PresetSQL) {
			buf.WriteString(generateSQLPreset(t))
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("failed to format generated code: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}
