package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNormalizePresets(t *testing.T) {
	// default empty -> all presets
	p, err := NormalizePresets(nil)
	require.NoError(t, err)
	assert.Equal(t, []Preset{PresetText, PresetJSON, PresetBinary, PresetBinder, PresetSQL}, p)

	// "all"
	p, err = NormalizePresets([]Preset{PresetAll})
	require.NoError(t, err)
	assert.Equal(t, []Preset{PresetText, PresetJSON, PresetBinary, PresetBinder, PresetSQL}, p)

	// "db" maps to "sql"
	p, err = NormalizePresets([]Preset{"db", "json"})
	require.NoError(t, err)
	assert.Equal(t, []Preset{PresetJSON, PresetSQL}, p)

	// invalid preset
	_, err = NormalizePresets([]Preset{"invalid"})
	assert.Error(t, err)
}

func TestGenerateSource(t *testing.T) {
	types := []*TypeInfo{
		{
			Name:        "UserID",
			PackageName: "models",
			Kind:        KindString,
			Underlying:  "string",
		},
		{
			Name:        "OrderID",
			PackageName: "models",
			Kind:        KindInt,
			Underlying:  "int64",
		},
		{
			Name:        "AccountID",
			PackageName: "models",
			Kind:        KindUint,
			Underlying:  "uint32",
		},
	}

	opts := GenerateOptions{
		PackageName: "models",
		Types:       types,
		Presets:     []Preset{PresetAll},
	}

	code, err := Generate(opts)
	require.NoError(t, err)
	assert.Contains(t, string(code), "// Code generated by typed-id. DO NOT EDIT.")
	assert.Contains(t, string(code), "package models")
	assert.Contains(t, string(code), "func (id UserID) String() string")
	assert.Contains(t, string(code), "func (id OrderID) MarshalJSONTo(in *jsontext.Encoder) error")
	assert.Contains(t, string(code), "func (id *AccountID) Scan(src any) error")

	// Verify we can write and parse as valid Go file
	tempDir := t.TempDir()
	outFile := filepath.Join(tempDir, "models_gen.go")
	err = os.WriteFile(outFile, code, 0o644)
	require.NoError(t, err)

	_, err = ParsePackage(tempDir)
	require.NoError(t, err)
}
